default: &default
development:
  <<: *default
  database: curators_development
test:
  <<: *default
  database: curators_test
production:
  <<: *default
  database: <%= ENV['CLOUDANT_URL_BACKUP'] %>/curators_production
